In [1]:
import numpy as np

In [2]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
np.__version__

'1.26.4'

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [14]:
np.arange(20,8)

array([], dtype=int32)

In [15]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [52]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [53]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [54]:
np.arange(10,10) 

array([], dtype=int32)

In [55]:
np.arange()

TypeError: arange() requires stop to be specified.

In [56]:
np.arange(10,30,5) 

array([10, 15, 20, 25])

In [57]:
np.arange(0,10,3) 

array([0, 3, 6, 9])

In [58]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [59]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [61]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
np.zeros([5,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
np.zeros([10,30])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [60]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [18]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [65]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [68]:
np.zeros(n1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [70]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [71]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [73]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [75]:
r=range(5)

In [76]:
for i in r:
    print(i)

0
1
2
3
4


In [77]:
list(range(5))

[0, 1, 2, 3, 4]

In [78]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
list(range(1,10,3))

[1, 4, 7]

In [80]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [22]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [24]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [25]:
random.rand(2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(2
               )

array([0.54739511, 0.07165019])

In [27]:
np.random.rand(3)

array([0.47729332, 0.33689967, 0.93941796])

In [28]:
np.random.rand(2,3)

array([[0.64207795, 0.21346037, 0.04864079],
       [0.98257104, 0.8344774 , 0.3997955 ]])

In [29]:
np.random.randint(3)

2

In [30]:
np.random.randint(2,10)

8

In [83]:
np.random.randint(2,20) 

5

In [31]:
np.random.randint(2,10,3)

array([8, 6, 5])

In [88]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [89]:
np.random.randint(-30,20,10) 

array([ 10, -13,  -2, -18, -26, -22, -29,   7,  -7, -13])

In [93]:
np.random.randint(20,30,10) 

array([21, 27, 25, 20, 20, 22, 27, 22, 21, 25])

In [91]:
np.random.randint(5,9)


7

In [86]:
np.random.rand(3)

array([0.95062436, 0.46082935, 0.84201575])

In [94]:
np.random.randint(10,21,3)

array([16, 20, 20])

In [87]:
np.random.rand(2)

array([0.28705639, 0.38214145])

In [95]:
np.random.randint(10,40,(10,10))

array([[19, 11, 11, 22, 20, 13, 27, 20, 12, 13],
       [33, 14, 34, 18, 25, 34, 34, 34, 17, 21],
       [15, 29, 31, 32, 29, 24, 23, 38, 10, 10],
       [39, 27, 25, 12, 30, 16, 13, 22, 20, 12],
       [15, 11, 26, 28, 26, 12, 28, 23, 31, 11],
       [23, 37, 15, 18, 22, 13, 16, 30, 22, 11],
       [30, 28, 30, 25, 10, 15, 37, 16, 23, 12],
       [16, 10, 14, 21, 29, 26, 24, 16, 25, 34],
       [30, 17, 28, 17, 31, 11, 35, 19, 15, 29],
       [12, 34, 16, 38, 14, 19, 34, 38, 31, 20]])

In [96]:
np.random.randint(1,100,(10,10))

array([[80, 14, 52, 19, 21, 52, 14, 22, 70, 49],
       [46, 32, 39, 43, 35, 34, 18, 81, 12, 66],
       [55, 21, 94, 74, 18, 92,  5, 62, 75, 64],
       [87, 53, 62, 68, 50, 82,  9, 72, 35, 96],
       [23, 35, 90, 35, 94, 29,  1, 43, 11, 51],
       [76, 62, 96, 39, 11, 28, 91, 74, 19,  8],
       [26, 80, 27, 51, 95, 46, 62, 50, 50,  5],
       [74, 28, 14,  2, 93, 24, 77, 11, 27, 57],
       [98, 82, 46, 55, 52, 96, 45, 36, 22, 63],
       [43, 48,  5, 24, 84, 72,  6, 46, 79, 58]])

In [32]:
np.random.randint(-30,2,10)

array([ -1, -21, -20,  -2, -30,  -4,  -6, -19, -20,  -2])

In [35]:
np.random.randint(10,40,(10,10))

array([[30, 35, 13, 32, 17, 35, 15, 33, 15, 17],
       [14, 30, 16, 11, 15, 26, 26, 13, 14, 39],
       [35, 32, 16, 25, 37, 30, 11, 36, 11, 24],
       [15, 10, 10, 31, 18, 36, 20, 31, 25, 16],
       [39, 38, 18, 19, 21, 34, 35, 24, 34, 12],
       [36, 15, 39, 27, 36, 20, 20, 26, 39, 17],
       [18, 33, 25, 16, 16, 28, 32, 18, 38, 14],
       [15, 16, 14, 22, 10, 24, 16, 35, 36, 28],
       [26, 38, 21, 39, 32, 37, 18, 21, 36, 18],
       [24, 37, 19, 10, 13, 33, 34, 21, 16, 35]])

In [36]:
m=np.random.randint(10,40,(10,10))
m

array([[17, 29, 26, 34, 20, 32, 26, 35, 16, 39],
       [32, 14, 21, 11, 31, 33, 18, 35, 32, 24],
       [31, 23, 36, 32, 36, 35, 38, 17, 35, 23],
       [23, 24, 33, 23, 24, 21, 11, 25, 33, 10],
       [19, 27, 36, 25, 35, 17, 20, 14, 35, 31],
       [34, 35, 35, 20, 19, 27, 35, 23, 25, 10],
       [10, 34, 39, 23, 11, 11, 19, 33, 10, 36],
       [33, 30, 38, 33, 34, 24, 39, 33, 10, 19],
       [25, 35, 37, 33, 33, 28, 20, 39, 30, 13],
       [23, 31, 32, 32, 32, 27, 17, 17, 12, 38]])

In [99]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [37]:
arr

array([0, 1, 2, 3, 4, 5])

In [38]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:

arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [41]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [42]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [43]:
m

array([[17, 29, 26, 34, 20, 32, 26, 35, 16, 39],
       [32, 14, 21, 11, 31, 33, 18, 35, 32, 24],
       [31, 23, 36, 32, 36, 35, 38, 17, 35, 23],
       [23, 24, 33, 23, 24, 21, 11, 25, 33, 10],
       [19, 27, 36, 25, 35, 17, 20, 14, 35, 31],
       [34, 35, 35, 20, 19, 27, 35, 23, 25, 10],
       [10, 34, 39, 23, 11, 11, 19, 33, 10, 36],
       [33, 30, 38, 33, 34, 24, 39, 33, 10, 19],
       [25, 35, 37, 33, 33, 28, 20, 39, 30, 13],
       [23, 31, 32, 32, 32, 27, 17, 17, 12, 38]])

In [44]:
b=np.random.randint(10,20,(5,4))
b

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12],
       [10, 14, 11, 18]])

In [45]:
b[:]

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12],
       [10, 14, 11, 18]])

In [46]:
b[1:4]

array([[11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12]])

In [47]:
b[-1:]

array([[10, 14, 11, 18]])

In [48]:
b[:-1]

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12]])

In [49]:
b[:-2]

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13]])

In [50]:
b[1,2]

15

In [51]:
b[1,3]

16

In [101]:
b

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12],
       [10, 14, 11, 18]])

In [102]:
b[1,-1]

16

In [103]:
b[-5,-3]

16

In [104]:
b

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12],
       [10, 14, 11, 18]])

In [105]:
b[-4,2]

15

In [106]:
b[-4,-2]

15

In [107]:
b[-4:2]

array([[11, 14, 15, 16]])

In [108]:
b[:]

array([[13, 16, 10, 12],
       [11, 14, 15, 16],
       [16, 11, 13, 13],
       [10, 11, 10, 12],
       [10, 14, 11, 18]])

In [109]:
a = np.random.randint(10,20,10)
a

array([12, 13, 15, 11, 11, 16, 19, 14, 17, 16])

In [110]:
id(a)

2588583358128

In [111]:
arr

array([0, 1, 2, 3, 4, 5])

In [112]:
arr2 = np.random.randint(0,100,(10,10))


In [113]:
arr2

array([[44, 33, 93, 35,  0, 62, 84, 97, 70,  9],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70],
       [17, 15, 35, 77, 28, 53, 58,  5, 42, 83],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [67, 36, 75, 51, 49, 62, 68, 41, 99, 59],
       [ 6, 29, 39, 93, 83, 98,  7,  7,  3, 79],
       [56, 12, 88, 92, 28, 97,  2, 80, 14,  0],
       [32, 37, 39, 16, 54,  9, 94, 44, 35, 78],
       [90, 20, 89, 63, 87, 61, 75, 36, 29, 98],
       [92, 14, 79, 35, 79,  3, 19, 63, 60, 46]])

In [114]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [115]:
arr[:4]

array([0, 1, 2, 3])

In [117]:
arr2[:]

array([[44, 33, 93, 35,  0, 62, 84, 97, 70,  9],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70],
       [17, 15, 35, 77, 28, 53, 58,  5, 42, 83],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [67, 36, 75, 51, 49, 62, 68, 41, 99, 59],
       [ 6, 29, 39, 93, 83, 98,  7,  7,  3, 79],
       [56, 12, 88, 92, 28, 97,  2, 80, 14,  0],
       [32, 37, 39, 16, 54,  9, 94, 44, 35, 78],
       [90, 20, 89, 63, 87, 61, 75, 36, 29, 98],
       [92, 14, 79, 35, 79,  3, 19, 63, 60, 46]])

In [119]:
arr2[0:5]

array([[44, 33, 93, 35,  0, 62, 84, 97, 70,  9],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70],
       [17, 15, 35, 77, 28, 53, 58,  5, 42, 83],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [67, 36, 75, 51, 49, 62, 68, 41, 99, 59]])

In [120]:
arr2[1,4]

35

In [121]:
arr2[-5,5]

98

In [123]:
arr2[-1,-2]

60

In [124]:
arr2[::-1]

array([[92, 14, 79, 35, 79,  3, 19, 63, 60, 46],
       [90, 20, 89, 63, 87, 61, 75, 36, 29, 98],
       [32, 37, 39, 16, 54,  9, 94, 44, 35, 78],
       [56, 12, 88, 92, 28, 97,  2, 80, 14,  0],
       [ 6, 29, 39, 93, 83, 98,  7,  7,  3, 79],
       [67, 36, 75, 51, 49, 62, 68, 41, 99, 59],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [17, 15, 35, 77, 28, 53, 58,  5, 42, 83],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70],
       [44, 33, 93, 35,  0, 62, 84, 97, 70,  9]])

In [125]:
arr2

array([[44, 33, 93, 35,  0, 62, 84, 97, 70,  9],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70],
       [17, 15, 35, 77, 28, 53, 58,  5, 42, 83],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [67, 36, 75, 51, 49, 62, 68, 41, 99, 59],
       [ 6, 29, 39, 93, 83, 98,  7,  7,  3, 79],
       [56, 12, 88, 92, 28, 97,  2, 80, 14,  0],
       [32, 37, 39, 16, 54,  9, 94, 44, 35, 78],
       [90, 20, 89, 63, 87, 61, 75, 36, 29, 98],
       [92, 14, 79, 35, 79,  3, 19, 63, 60, 46]])

In [ ]:
arr2[::-2]

array([[92, 14, 79, 35, 79,  3, 19, 63, 60, 46],
       [32, 37, 39, 16, 54,  9, 94, 44, 35, 78],
       [ 6, 29, 39, 93, 83, 98,  7,  7,  3, 79],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [87,  0, 40, 94, 35, 91, 37, 74, 27, 70]])

In [127]:
arr2[::-3]

array([[92, 14, 79, 35, 79,  3, 19, 63, 60, 46],
       [56, 12, 88, 92, 28, 97,  2, 80, 14,  0],
       [34, 88, 85, 81, 20, 98, 13, 22, 83, 38],
       [44, 33, 93, 35,  0, 62, 84, 97, 70,  9]])

In [128]:
arr

array([0, 1, 2, 3, 4, 5])

In [129]:
arr.max()

5

In [130]:
arr.min()

0

In [131]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [132]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [133]:
arr

array([0, 1, 2, 3, 4, 5])

In [134]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [135]:
arr.reshape(6,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [136]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [137]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [141]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [142]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [143]:
mat = np.arange(0,100).reshape(10,10) 

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
row=4
col=5

In [147]:
mat[row,col]

45

In [148]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
col=6

In [150]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [151]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [152]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [153]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [154]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [155]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [156]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [157]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [159]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [160]:
mat[1,4]

14

In [163]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [166]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [168]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [170]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [171]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [175]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [176]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [177]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [178]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [179]:
mat[0,1]

1

In [180]:
mat[1,6]

16

In [181]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [183]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [185]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [186]:
mat[3,5]

35

In [187]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [188]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[1:2,2:4] 

array([[12, 13]])

In [190]:
mat[2:3,2:3]

array([[22]])

In [191]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [192]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[2:3,4:5]

array([[24]])

In [195]:
id(mat)

2588584483824

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [198]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [200]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [201]:
mat[mat==50]

array([50])

In [202]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [203]:
a1 = mat[mat>50] 
a1

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [204]:
a1 = mat[mat<=50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [205]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 3132


In [206]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [207]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [208]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000025AB3A1FCC0>


In [209]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
